### ISSUE TITLE
[Bug] When Left/Right Separation is greater than 0, position of XHB pushed to the right on login

### ISSUE THREAD

**Issue by ryankhart** [ItsBexy/CrossUp#14]
I also noticed that when I change the Left/Right Separation setting while in the /hudlayout configuration and the L/R Separation is > 0, the position of the XHB snaps off to the left. Then, when I adjust the position of the XHB in /hudlayout it snaps back to the right. It seems to me that these two issues may be one in the same. If we fix one of these, they both might be fixed.

**Comment by ItsBexy** [comment]
The issues are definitely related. I think I may have fixed this more reliably in 0.3.0.0, but we'll see how it plays out.

What's happening with HUD shenanigans is: When the "split" value is increased, the entire hotbar actually moves to the left while simultaneously widening rightward. This creates the effect that it's simply widening from the centre without moving.

The problem is, that still changes the bar's X coordinates as far as the HUD layout interface is concerned. And this meant it would consistently snap to the left anytime the Hud layout interface was opened. So I wrote a corrective function to automatically snap it back to the right each time. This has _mostly_ worked.

However, on login, things can be a little random. There's sometimes a gap of a few frames between the moment the Cross Hotbar loads into existence, and the moment the game actually moves it into position as per the user's Hud settings. And if CrossUp does anything to the bar's position inbetween these two events, the game will overwrite the position a moment later, and ta-dah, you end up with an off-kilter bar. It can be fixed easily enough by switching back and forth between Hud profiles, but obviously that's annoying.

So in v0.3.0.0, CrossUp will wait until the Cross Hotbar has been fully loaded AND positioned according to the user's Hud settings, and only then will the plugin get the greenlight to start moving bars around. I'm hoping that will be enough to fix the issue for good, but like I said, we'll see.

**Comment by ItsBexy** [comment]
Further fixes in place for 0.3.0.2. On logout/uninstall, the plugin will now store the current X positions of the Cross Hotbar and it's primary node, so that it can accurately restore them on login. It'll take at least one logout for the plugin to store those values, so you might not see this fix take effect next time you login, but it should do its thing for all subsequent logins.

**Comment by ItsBexy** [comment]
The latest update (0.4.2.0) should firmly and finally fix this issue. Activating the bar separation feature will now cause the plugin to override the HUD setting for the bar's horizontal position, anchoring it to a position of your choice no matter what.
