### ISSUE TITLE
[Suggestion] Hide Unassigned Slots 

### ISSUE THREAD

**Issue by kevinkickback** [ItsBexy/CrossUp#16]
Would it be possible to add an option to hide unassigned slots just like the regular hotbar?

**Comment by ItsBexy** [comment]
I've added this in 0.3.1.0, thanks for the request!

It was a little tricky because the Cross Hotbar slots have to be hidden a slightly different way than Mouse/KB Action bar slots, and they still have to reappear while dragging/dropping. I think I've ironed out the major visual oddities, but be sure let me know if you spot anything weird happening with the setting active.

**Comment by kevinkickback** [comment]
Thank you for all your hard work! I really enjoy this plugin. 

After initial testing the only "issue" I've found is that the unassigned slots on the WXHB do not automatically hide themselves again after dragging/dropping actions onto the main XHB. Pressing either L or R re-hides them though. Just a small quirk I noticed but other than that it is working flawlessly.

https://user-images.githubusercontent.com/12663557/172088861-c2cd2edf-ad35-421b-8103-81923634c60d.mp4

Thank you again.
