### ISSUE TITLE
Make Expanded Cross Hotbar follow visibility settings from the borrowed Hotbar and/or the rest of the Cross Hotbar

### ISSUE THREAD

**Issue by thedaryen** [ItsBexy/CrossUp#20]
Basically, the "always display Cross Hotbar" setting works in such a way that doesn't allow it to be hidden in the same way that other HUD elements are (by macros or Character Settings). It'd be useful if it followed either the visibility settings from the borrowed Hotbars, or from the Cross Hotbar itself. I personally switch back and forth a minimal HUD Layout that only display hotbars when I press R2/L2, and when in duties, a "always display cross hotbar" layout. However, with CrossUp enabled, my minimal layout isn't as minimal, because the Expanded will always be shown regardless of other settings unless I manually open CrossUp settings and untick the "always display" box every time, then tick it again when on duty.

**Comment by ItsBexy** [comment]
Hi! This is something that's already fixed in the Net6 version of the plugin, which I believe isn't live on Dalamud yet, but will be as of FFXIV 6.2. I made a few adjustments to ensure that the Expanded bars follow the visibility of the main Cross Hotbar as closely as possible.

As long as 6.2 doesn't disrupt CrossUp's functionality in some way, you should be seeing the fix this week, whenever plugins return post-patch (or shortly after).
